name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
       major_pattern: "major:"
       minor_pattern: "feat:"
       format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
        
    - name: Docker login
      env:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       #NEW_VERSION: ${{ steps.version.outputs.version}}
      run: 
       #echo "iniciando login"
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
       #echo "New version: $NEW_VERSION!!1!"
       #echo "fin del login"
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t yjd7/docker-graphql:v1.0.2:$NEW_VERSION .
    #    docker build -t yjd7/docker-graphql:v1.0.2:latest .
        
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push yjd7/docker-graphql:$NEW_VERSION
   #     docker push yjd7/docker-graphql:latest
   # - name:  Build Docker Image
   #   run: 
   #     #docker build -t yjd7/docker-graphql:v1.0.2
   #     docker build -t yjd7/docker-graphql .
#
   # - name: Push Docker Image
   #   run: 
   #    #docker push yjd7/docker-graphql:v1.0.2 
   #    docker push yjd7/docker-graphql

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#docker run -p 3000:3000 yjd7/docker-graphql:v1.0.2