name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker login
      env:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: 
       #echo "iniciando login"
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
       #echo "fin del login"

    - name:  Build Docker Image
      run: 
        #docker build -t yjd7/docker-graphql:v1.0.2
        docker build -t yjd7/docker-graphql .

    - name: Push Docker Image
      run: 
       #docker push yjd7/docker-graphql:v1.0.2 
       docker push yjd7/docker-graphql

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#docker run -p 3000:3000 yjd7/docker-graphql:v1.0.2